repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        language: system
        entry: pipenv run black
        types: [python]

      - id: flake8
        name: flake8
        language: system
        entry: pipenv run flake8
        types: [python]

      - id: mypy
        name: mypy
        language: system
        entry: pipenv run mypy
        types: [python]

default_language_version:
  python: python3.8

default_stages:
  - "commit"
